batch_size: 1
model_name: "/data/chy/gpt-neo"
# model_name: "EleutherAI/gpt-neo-125M"
output_file: /data/chy/chy/EPR/mtop/gptneo_score.json
example_file: /data/chy/chy/EPR/mtop/bm25_mtop.json
setup_type: qa
task_name: mtop

dataset_reader:
  _target_: src.dataset_readers.scorer_dsr.ScorerDatasetReader
  example_file: ${example_file}
  task_name: ${task_name} 
  model_name: ${model_name}
  setup_type: ${setup_type}
model:
  _target_: transformers.AutoModelForCausalLM.from_pretrained
  pretrained_model_name_or_path: ${model_name}

